# Create image based on node image
FROM node:current-alpine3.10 as build

# Set working directory
WORKDIR /bindays
ADD . /bindays

# Add /bindays/node_modules/.bin to environment variables
ENV PATH /bindays/node_modules/.bin:$PATH

# Install all app dependencies
COPY package.json /bindays/package.json
RUN yarn install
#RUN npm install react-scripts -g
RUN  apk update && apk add bash vim git \
    && cd $WORKDIR \
    && yarn install --ignore-engines;

# Build the app
RUN yarn run build

# Create image based on nginx and deploy our built React app
FROM nginx:1.17-alpine

COPY --from=build /bindays/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
